### ISSUE TITLE
WebTorrent doesn't work in Firefox?

### ISSUE THREAD

**Issue by feross** [retrohacker/peerweb.js#1]
Nice project!

What is the issue you experience in Firefox?

WebTorrent should work in Firefox just fine. You can try https://webtorrent.io or https://instant.io in Firefox stable (44) and see that it works. Let's figure out why WebTorrent isn't working for you.

**Comment by retrohacker** [comment]
Hey @feross!

> Aside: We met briefly at NodeConf 2014. You introduced me to this project then, and I ranted about my MPI implementation over websockets (was a WIP I never finished): https://github.com/retrohacker/CloudCompute2

I haven't been able to get webtorrent to work on iceweasel (Firefox 38.5.0) through the debian repo nor Firefox 45.0a2. I just downloaded 44 and had the same experience.

Uploading a file to instant.io appears to work fine, and it is rendered in the preview pane. I then open another tab of instant.io and paste in the info_hash. Nothing happens. No errors are logged, but the download never begins.

Here is a screenshot of the console:

![docker_node1](https://cloud.githubusercontent.com/assets/1081565/12771044/da3e0d12-c9f3-11e5-8219-66d9df691ecd.png)

I was planning on stepping through the code to see where things are going awry but I haven't had a chance yet.

Also, is there a way to increase the log level of the library?

**Comment by feross** [comment]
Nice, cool that we've met before!

To show all logs, run `localStorage.DEBUG = '*'`, then refresh the page.

**Comment by feross** [comment]
You might want to try with a fresh Firefox profile, just in case you've changed some of the "about:config" settings.

**Comment by retrohacker** [comment]
Just an update. I spent about 10 minutes last night looking at it. `localStorage.DEBUG = '*'` doesn't appear to have an effect.

Though I've started seeing a lot of `the connection to wss://... was interupted while the page was loading`. This seems to be independent of the problem, since it doesn't happen everytime.

**Comment by retrohacker** [comment]
Well this is unexplainable. After about 30 minutes of stepping through the library, instant.io started working in firefox.

It may have been a setting I had somewhere. I was switching back and forth between versions of firefox but they were using the same profile, something may have gotten toggled in that process.

Right now, the problem seems to be `router.js` is preventing `wss://` from establishing a connection in firefox. But that is a problem with my stuff, not webtorrent!

**Comment by retrohacker** [comment]
Ah, and I solved the debug issue. Its supposed to be lower case :wink: `localStorage.debug = "*"`

**Comment by retrohacker** [comment]
This is super weird, because `ServiceWorker`s shouldn't be able to see requests that aren't in their scope, let alone alter them. I wonder if this is a bug in firefox.

**Comment by retrohacker** [comment]
This is a known bug and the fix will land in 44.0.1

https://bugzilla.mozilla.org/show_bug.cgi?id=1243942

**Comment by feross** [comment]
@retrohacker Nice work debugging this!

**Comment by retrohacker** [comment]
Thanks @feross :smile:
